version: "3.7"

services:
  mysql:
    image: mysql:5.7
    command: # 명령어 실행
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: blue-mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=udl
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/seoul
    platform: linux/x86_64 # build 후 삭제